version: 2.1
jobs:
  build:
    docker:
      - image: node:latest
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Set executable permission for jest
          command: chmod +x ./node_modules/.bin/jest
      - run:
          name: Run tests
          command: npx jest
